services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devnote
      POSTGRES_USER: devnote
      POSTGRES_PASSWORD: devnote
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
